FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y netcat
RUN pip install kafka-python requests

WORKDIR /weather

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer.py .

CMD ["python", "consumer.py"]